name: Planck API tests

on:
  push:
    branches:
      - '*'           # All branches
    paths-ignore:
      - '**/main'
      - '**/develop'  # Exclude 'main' and 'develop'

  pull_request:
    branches:
      - develop       # Trigger on pull requests to develop
      - main          # Trigger on pull requests to main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up PostgreSQL
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '13'  # Specify the version of PostgreSQL
        postgresql db: 'test_db'   # Name of the test database
        postgresql user: 'postgres' # Default PostgreSQL user
        postgresql password: 'postgres' # Password for the default user

    - name: Configure database
      run: | 
        echo '{ "ENGINE": "django.db.backends.postgresql_psycopg2", "DB_HOST": "localhost", "DB_PORT": 5432, "DB_USER": "postgres", "DB_PASSWORD": "postgres", "DB_NAME": "test_db"}' > configs/development_env/database.json

    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      env: # Set environment variables for database connection
        DATABASE_URL: postgres://postgres:postgres@localhost/test_db
      run: |
        python manage.py test --verbosity=2
